name = "stanza-libfive"
version = "0.1.5"
[dependencies]
stanza-utils = "jackbackrack/stanza-utils|0.1.3"
stanza-geom = "jackbackrack/stanza-geom|0.1.12"
stanza-gfx = "jackbackrack/stanza-gfx|0.1.10"
